import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
        /**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get one command-line argument: an int value
 * 	that determines how many families to simulate.
 */

		int numberoffamily = Integer.parseInt(args[0]);
		int countotalchildern = 0 , count2ch = 0 , count3ch = 0 , count4ch = 0 ;
		for (int i=0;i<numberoffamily;i++) //using my exsist code to genrate number of childern for family that i got
		{
		int countlocalchild = 0;
		boolean boy = true, girl = true; //checking if i have both girl and boy
			while (boy || girl)
			{	

				double isgender = generator.nextDouble();
				if(isgender > 0.5)
				{
					girl = false;
				}
				
				else
				{	
					boy = false;
				} 	
				countlocalchild ++;
				countotalchildern ++;

			}

			if (countlocalchild == 2 ) //checking for which group of family he belong
					count2ch++;
			if (countlocalchild == 3 )
					count3ch++;
			if (countlocalchild > 3 )
					count4ch++;	
		}
		double numberoffamilydouble = 0.0 + numberoffamily; //casting the number of family to double and printing the average number and the number of each family
		System.out.println("Average: "+ countotalchildern/numberoffamilydouble +" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+count2ch);
		System.out.println("Number of families with 3 children: "+count3ch);
		System.out.println("Number of families with 4 or more children: "+count4ch);
		int commonfamily = Math.max( (Math.max(count2ch,count3ch)),count4ch); //checking which of the number of child is most common
		if (commonfamily == count2ch)
			System.out.println("The most common number of children is 2.");
			else if (commonfamily == count3ch)
					System.out.println("The most common number of children is 3.");
						else if (commonfamily == count4ch)
						System.out.println("The most common number of children is 4 or more.");


  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
